# example netlify.toml
[build]
  command = "yarn build"
  functions = "functions" # not strictly required but putting this for convenience
  publish = "build"

# Uncomment to use this redirect for Single Page Applications like create-react-app. 
# Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
